---
- name: Create host folders for suricata configs and rules
  file:
    path: "{{ host_container_root }}/{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ suricata.name }}"
    - "{{ suricata.name }}/config"

- name: pull custom images
  docker_image:
    name: "{{ item }}"
    source: pull
    force_source: yes
  retries: 15
  delay: 2
  register: docker_pull
  until: not docker_pull.failed
  loop:
    - "{{ suricata_image }}"
    - "{{ suricata_shipper_image }}"
    - "{{ suricata_update_image }}"

- set_fact:
    meerkat: 
      data_vol: "data-{{ suricata.name }}"
      rule_vol: "rules-{{ suricata.name }}"
      socket_vol: "sockets-{{ suricata.name }}"
      data_socket_vol: "event-sockets-{{suricata.name}}"
    kafka_brokers: "{{ suricata.kafka.brokers if 'kafka' in suricata else ['localhost:9092'] }}"
    kafka_topic: "{{ suricata.kafka.topic if 'kafka' in suricata else 'peek' }}"
    ela_hosts: "{{ suricata.elastic.hosts if 'elastic' in suricata else ['http://localhost:9200'] }}"
    ela_index: "{{ suricata.elastic.index if 'elastic' in suricata else 'suricata' }}"

- name: Create volumes for suricata
  docker_volume:
    name: "{{ item }}"
  loop:
    - "data-{{ suricata.name }}"
    - "rules-{{ suricata.name }}"
    - "sockets-{{ suricata.name }}"
    - "event-sockets-{{ suricata.name }}"

- name: Deploy suricata-update configs
  template:
    src: "{{ item.src }}"
    dest: "{{ host_container_root }}/{{ suricata.name }}/config/{{ item.dest }}"
    mode: 0644
  loop:
    - src: update.j2
      dest: update.yaml
    - src: disable.j2
      dest: disable.conf
  register: suricata_update_config

- name: Deploy suricata-update configs
  template:
    src: "{{ item.src }}"
    dest: "{{ host_container_root }}/{{ suricata.name }}/config/{{ item.dest }}"
    mode: 0644
  loop:
    - src: suricata.j2
      dest: suricata.yaml
  notify: 
    - restart suricata
  register: suricata_config

- set_fact:
    suricata_volumes: 
      - "{{ host_container_root }}/{{ suricata.name }}/config/suricata.yaml:/etc/suricata/suricata.yaml:ro"
      - "rules-{{ suricata.name }}:/var/lib/suricata:ro"
      - "data-{{ suricata.name }}:{{ suricata_log_dir }}:rw"
      - "sockets-{{ suricata.name }}:{{ suricata_socket_dir }}:rw"
    suricata_socket_volumes:
      - "event-sockets-{{ suricata.name }}:/var/lib/peek:rw"

- set_fact:
    suricata_extended_volumes: "{{ suricata_volumes + suricata_socket_volumes }}"

- name: Run kafka shipper for suricata through unix socket output
  docker_container:
    name: "{{ suricata.name }}-peek-shipper"
    image: "{{ suricata_shipper_image }}"
    state: started
    restart_policy: unless-stopped
    command: run
    network_mode: host
    env:
      PEEK_INPUT_UXSOCK_ENABLED: 'true'
      PEEK_INPUT_UXSOCK_OVERWRITE: 'true'
      PEEK_STREAM_SURICATA_UXSOCK: "/var/lib/peek/{{ suricata.global_log_socket if 'global_log_socket' in suricata else 'suricata-events.socket' }}"
      PEEK_PROCESSOR_COMPAT_LOGSTASH: 'true'
      PEEK_OUTPUT_KAFKA_ENABLED: "{{ 'true' if 'kafka' in suricata else 'false' }}"
      PEEK_OUTPUT_KAFKA_HOST: "{{ kafka_brokers | join(' ')}}"
      PEEK_OUTPUT_KAFKA_TOPIC: "{{ kafka_topic }}"
      PEEK_OUTPUT_ELASTIC_ENABLED: "{{ 'true' if 'elastic' in suricata else 'false' }}"
      PEEK_OUTPUT_ELASTIC_HOST: "{{ ela_hosts | join(' ')}}"
      PEEK_OUTPUT_ELASTIC_PREFIX: "{{ ela_index }}"
      PEEK_OUTPUT_ELASTIC_MERGE: 'true'
    volumes: "{{ suricata_socket_volumes }}"
  when: "('kafka' in suricata and 'brokers' in suricata.kafka and suricata.kafka.brokers | length > 0) or ('elastic' in suricata and 'hosts' in suricata.elastic and suricata.elastic.hosts | length > 0)"

- name: Run container for suricata
  docker_container:
    name: "{{ suricata.name }}"
    image: "{{ suricata_image }}"
    state: started
    network_mode: host
    restart_policy: unless-stopped
    privileged: yes 
    capabilities:
      - net_admin
      - sys_nice
    volumes: "{{ suricata_extended_volumes }}"
    command: "--af-packet -vvv"

- name: Deploy suricata rules
  docker_container:
    name: "{{ suricata.name }}-update"
    image: "{{ suricata_update_image }}"
    volumes:
      - "{{ host_container_root }}/{{ suricata.name }}/config/update.yaml:/etc/update.yaml:ro"
      - "{{ host_container_root }}/{{ suricata.name }}/config/disable.conf:/etc/disable.conf:ro"
      - "rules-{{ suricata.name }}:/var/lib/suricata:rw"
    command: "-c /etc/update.yaml"
    detach: no
    auto_remove: no
  register: restult
  tags:
    - suricata
    - rule_update

# skip if suricata config is changed, handler will restart the daemon anyway leading to wasted deploy time and even socket connect fail
- name: Reload suricata on rule update
  docker_container:
    name: "{{ suricata.name }}-reloader"
    image: "{{ suricata_image }}"
    detach: no
    auto_remove: no
    entrypoint:
      - suricatasc
      -  "-c reload-rules"
    volumes:
      - "{{ host_container_root }}/{{ suricata.name }}/config/suricata.yaml:/etc/suricata/suricata.yaml:ro"
      - "sockets-{{ suricata.name }}:{{ suricata_socket_dir }}:rw"
  when: not suricata_config.changed and not docker_pull.changed

- name: cleanup
  docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ suricata.name }}-update"
    - "{{ suricata.name }}-reloader"
