---
- name: pull images
  docker_image:
    name: "{{ packetbeat_image }}"
    source: pull
    force_source: yes
  retries: 15
  delay: 2
  register: docker_pull
  until: not docker_pull.failed
  tags:
    - pull

- name: Create host folders for packetbeat configs
  file:
    path: "{{ host_container_root | mandatory }}/{{ packetbeat.name }}"
    state: directory
    mode: 0755

- name: Create packetbeat config
  template:
    src: packetbeat.j2
    dest: "{{ host_container_root | mandatory }}/{{ packetbeat.name }}/packetbeat-{{ id }}.yml"
  notify:
    - restart packetbeat
  loop: "{{ packetbeat.interfaces | mandatory }}"
  vars:
    packetbeat_iface: "{{ item }}"
    id: "{{ packetbeat.interfaces.index(item) }}"

- name: Run container for packetbeat
  docker_container:
    name: "{{ packetbeat.name }}-sensor-{{ id }}"
    hostname: "{{ packetbeat.name }}-sensor-{{ id }}"
    image: "{{ packetbeat_image }}"
    state: "{{ packetbeat.enable | default(true) | ternary('started', 'stopped', 'stopped') }}"
    network_mode: host
    restart_policy: unless-stopped
    capabilities:
      - net_admin
      - net_raw
    volumes:
      - "{{ host_container_root | mandatory }}/{{ packetbeat.name }}/packetbeat-{{ id }}.yml:/etc/packetbeat.yml:ro"
    command: "-c /etc/packetbeat.yml"
  loop: "{{ packetbeat.interfaces | mandatory }}"
  vars:
    id: "{{ packetbeat.interfaces.index(item) }}"
