---
- name: restart zeek
  command: "docker restart {{ zeek.name }}-sensor-{{ item }}"
  loop: "{{ zeek.interfaces | mandatory }}"

- name: restart zeek filebeat
  command: "docker restart {{ zeek.name }}-shipper-filebeat-{{ item }}"
  loop: "{{ zeek.interfaces | mandatory }}"
