---
- name: restart moloch capture
  shell: "docker restart {{ moloch_container_name }}-capture"

- name: restart moloch viewer
  shell: "docker restart {{ moloch_container_name }}-viewer"

- name: restart moloch wise
  shell: "docker restart {{ moloch_container_name }}-wise"
