---
- name: pull kibana image
  docker_image:
    name: "{{ kibana_image }}"
    source: pull
  retries: 15
  delay: 2

- name: Deploy docker containers for kibana in elastic cluster
  docker_container:
    name: "{{ kibana_container_name }}"
    hostname: "{{ kibana_container_name }}"
    image: "{{ kibana_image }}"
    purge_networks: yes
    state: started
    restart_policy: unless-stopped
    network_mode: "{{ item.host_network | default(false) | ternary('host', 'bridge', 'none') }}"
    networks: "{{ item.networks | default([]) }}"
    published_ports: "{{ item.expose_kibana | default([]) }}"
    env:
      ELASTICSEARCH_HOSTS: "{{ item.kibana_elasticsearch_hosts | mandatory | join(',') }}"
  loop: "{{ elastic_clusters }}"
  vars:
    elastic_node_id: "{{ '0' if item.singlehost | default(false) else item.node_id | mandatory }}"
    kibana_container_name: "{{ item.name }}-{{ elastic_node_id }}-kibana"
  when: item.singlehost | default(false) or inventory_hostname in item.hosts | default([])
