---
- name: pull kibana image
  docker_image:
    name: "{{ kibana_image }}"
    source: pull
  retries: 15
  delay: 2

- name: Deploy docker containers for kibana in elastic cluster
  docker_container:
    name: "{{ item.name }}-{{ item.node_id | mandatory }}-kibana"
    hostname: "{{ item.name }}-{{ item.node_id | mandatory }}-kibana"
    image: "{{ kibana_image }}"
    purge_networks: yes
    state: started
    restart_policy: unless-stopped
    network_mode: "{{ item.host_network | default(false) | ternary('host', 'bridge', 'none') }}"
    networks: "{{ item.networks | default([]) }}"
    published_ports: "{{ item.expose_kibana | default([]) }}"
    env:
      ELASTICSEARCH_HOSTS: "{{ item.kibana_elasticsearch_hosts | mandatory | join(',') }}"
  loop: "{{ elastic_clusters }}"
  when: not item.singlehost and inventory_hostname in item.hosts | default([])

- name: Deploy docker container for kibana node
  docker_container:
    name: "{{ item.name }}-kibana-0"
    hostname: "{{ item.name }}-kibana-0"
    image: "{{ kibana_image }}"
    purge_networks: yes
    state: started
    restart_policy: unless-stopped
    networks: "{{ item.networks | default([]) }}"
    published_ports: "{{ item.expose_kibana | default([]) }}"
    env:
      ELASTICSEARCH_HOSTS: "{{ item.kibana_elasticsearch_hosts | mandatory | join(',') }}"
      SERVER_HOST: 0.0.0.0
  loop: "{{ elastic_clusters }}"
  when: item.singlehost
