---
- name: Create host folders for zeek configs
  file:
    path: "{{ host_container_root | mandatory }}/{{ zeek.name }}"
    state: directory
    mode: 0755

- name: Create zeek entry script
  template:
    src: local.j2
    dest: "{{ host_container_root | mandatory }}/{{ zeek.name }}/local.zeek"
  notify:
    - restart zeek

- name: Run container for zeek
  docker_container:
    name: "{{ zeek.name }}-sensor-{{ id }}"
    hostname: "{{ zeek.name }}-sensor-{{ id }}"
    image: "{{ zeek_image }}"
    state: "{{ zeek.enable | default(true) | ternary('started', 'stopped', 'stopped') }}"
    network_mode: host
    restart_policy: unless-stopped
    capabilities:
      - net_admin
    volumes:
      - "{{ zeek.name }}-{{ id }}-data:/pcap:rw"
      - "{{ host_container_root | mandatory }}/{{ zeek.name }}/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek:ro"
    command: "-C -i {{ item }} local"
  loop: "{{ zeek.interfaces | mandatory }}"
  vars:
    id: "{{ zeek.interfaces.index(item) }}"
