# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME="frankenstack-singlehost"
CPU=8
MEM=8196
VERBOSE=false

$script = <<-SCRIPT
apt-get update
apt-get install -y python3 python3-pip
pip3 install ansible
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define NAME do |box|
    box.vm.box = "debian/buster64"
    box.vm.hostname = NAME
    box.vm.synced_folder ".", "/vagrant", type: "sshfs"
    box.vm.provider :virtualbox do |vb, override|
      override.vm.network :private_network, ip: "192.168.34.10"
      vb.customize ["modifyvm", :id, "--memory", MEM]
      vb.customize ["modifyvm", :id, "--cpus", CPU]
    end
    box.vm.provider :libvirt do |v, override|
      override.vm.network :private_network, ip: "192.168.35.10"
      v.memory = MEM
      v.cpus = CPU
    end
    config.vm.provision "shell", inline: $script
    config.vm.provision :ansible_local do |ansible|
      ansible.install = false
      ansible.install_mode = "pip"
      ansible.playbook = "./play_bootstrap_singlehost.yml"
      ansible.become = true
      ansible.verbose = VERBOSE
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
    config.vm.provision :ansible_local do |ansible|
      ansible.playbook = "./play_deploy_singlehost.yml"
      ansible.become = true
      ansible.verbose = VERBOSE
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
  end
end
