---
elastic_templates:
  core:
    index_patterns:
    - filebeat-*
    - winlogbeat-*
    - events-*
    - suricata-*
    - logstash-*
    - syslog-*
    mappings:
      dynamic_templates:
      - message_field:
          mapping:
            norms: 'false'
            type: text
          match_mapping_type: string
          path_match: message
      - string_fields:
          mapping:
            fields:
              keyword:
                ignore_above: 256
                type: keyword
            norms: 'false'
            type: text
          match: '*'
          match_mapping_type: string
      properties:
        '@timestamp':
          type: date
        '@version':
          type: keyword
    order: 0
    settings:
      index: "{{ elastic_template_settings }}"
      mapping:
        total_fields:
          limit: 4000
    version: 0
  suricata:
    index_patterns:
    - '*-suricata-*'
    - suricata-*
    mappings:
      properties:
        dest_ip:
          fields:
            keyword:
              ignore_above: 256
              type: keyword
          type: ip
        src_ip:
          fields:
            keyword:
              ignore_above: 256
              type: keyword
          type: ip
        payload:
          type: binary
    order: 15
    version: 0
  windows:
    index_patterns:
    - '*-windows-*'
    - '*-winlogbeat-*'
    - winlogbeat-*
    mappings:
      properties:
        Keywords:
          type: text
        winlog.event_data.param1:
          type: text
        winlog.event_data.param2:
          type: text
        winlog.event_data.param3:
          type: text
    order: 15
    version: 0
